[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "01af548ee83126fd01803f111acdb676258a8c52"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "b733a4ad486e6e4c8d9168c1f70333e7e6e64331c04a068ea608e8b820933c21"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "be45c8d24869df951113fb8ff30ddda299db9af7"
os = "macos"

    [[Zlib.download]]
    sha256 = "4487aba8b584ec732ea3bb567e9b98dd9e23f256294841adb84e7cf86ca6451a"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.x86_64-apple-darwin14.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "5bb306990e2c801cae0f5e6d0dd93bd971540649"
os = "windows"

    [[Zlib.download]]
    sha256 = "4971a6447699fd9a806199e8a196fcd5fd1b0b3cc5a87cd5d6d78193a448b093"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "22d19a03bf3b22d622a7ef11520cea511e24fae8"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "21f91fad2fd1a2903a72b1b9dbb833dbc81df115268a9e3e80350d9a5b71d950"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "e0bc0363ed98f2b962db1859cf7c0df4a806560d"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "8deea79e1172972634e0ced27e756139cf1e205ee6b0ecc5601835c72fe42962"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "02daa918cd44a5fc0736deca451ab368db1016cf"
os = "windows"

    [[Zlib.download]]
    sha256 = "1010aa960a0c721a88dd9c46c6d0b3bd209e8b9f2ed27a8f9a5e9523dabc8f0c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "2367492160f72c841b46540550f16f4d1c10d5be"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "2854a41a7f15430aed0df4e5d9208b20afb27123941ce71af4b0c99dcf4a3b28"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "a629ae8882119fb19375ac5dd7fb424b4c412146"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "9c87da9a21351a25fb6a1c806f14421da345649c3c6f4c8d83e0aa3e00b95922"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.x86_64-unknown-freebsd11.1.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "ffefb2e96a102c1c27591061d25e657422668ffa"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "627d93d9981ca5d0b19ead1356bffaacf8dd66e5627b60eadb449cc8618d8ee8"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.arm-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "0fa425508c4af8c1c331e198a4b5d0b7ff5ecbb4"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "91fcbb2d4720102deb5af81996f40b0ec11410ab8278f48b0b1cd08ffd01af45"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "8f4277c123a30377fe061dde4c1e9a8f00ae08bd"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "12f0c3aa21aa4609b4eb4363f3ce47f8b648ee82cdaf46a2c60dc7a0d81f84ef"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "6cc35615452a57a283e0635a31e2a8ae459c6979"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "d179217caa04f5aa5fae6b7851c0344f142fca635f0561c5f4f14a86bb534d7b"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "2b59515402195649a67954af4963600a0c8ab31a"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c6210cadb32f5a8098cbbe7422d2f0ff4c029af463e740e211692a2cfaea9223"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+5/Zlib.v1.2.11.arm-linux-gnueabihf.tar.gz"
