[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "71fc2b3f2c79398536db77557600200727459fba"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "2877825f116533cd226b6faecad09c56d09b20f249f3f3c5a9d2c57721202fb3"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "6517f0dc8312fb4060bc28f70b61d37ffda21d7e"
os = "macos"

    [[Zlib.download]]
    sha256 = "0855b16e64adeb166bf09a026218379504f064accbcd0b9c2b4cd936d7d9c73f"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.x86_64-apple-darwin14.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "3c7cf1a9fa1a8a12646dbc50b683cd87d07d8d35"
os = "windows"

    [[Zlib.download]]
    sha256 = "d07c079603f95d6eac7b996b1016df52c309426fcfb190fa2014552ea9168687"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "583eaeda9c5ad3d39c3222d94c757f92589dc49b"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "19ac76227de4614aa9c6e9e26656071ee64c9e8e400b4359caa0c07b82f7bf06"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "c9c207d357024846ea67af7c5f8e8eceb0b47515"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "ca128802c42f0cddff43459de1ca4af45feb3cf12fcc3bd6a1fa3b7a6ee012ac"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "1f9eca40f01c44b51d647d34717d480a14f3c265"
os = "windows"

    [[Zlib.download]]
    sha256 = "c66b00309557103af44fe3ef0378d7e7cd2293dec3447caab4e0fdfa10732d07"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "05f9f5738930652f92198922e098bdb58237b61c"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "61cfb2b33e72767508b7e5e912530a12ac658e350bee255d697959d6c19fa94d"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "cebfb007bd2dcec5726ade92ac2ad4380cfd3115"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "ce12d6c4b1d7dad0e40db66428a829e478835c41df74c2e997a322ce56333df6"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.x86_64-unknown-freebsd11.1.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "783fc6241e30dcfcad3a487303dacdc4326db062"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "f7f17f41923bdcba258a0b579b5e342917abcf97185cf28e7a4cc885132bc4cb"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.arm-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "0a30cc400110e65e3a64944b68bf3ddc6ba3aa01"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "d8820c6cc39858cb0f47ca29308ad8f0abfc6f83bd8ebbeed8d26b3573a12e18"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "06d7ccf97de7e140eac6e5b88b87821899309181"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "afd0c604b37b44bf5f4cf98f9799edf5ce5596827ebc4958ee77a5594dd6bb6d"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0b37c5d1d4b4fdbe19ddb31465f68fcdf1bc1878"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "ce9a2e426ae33779d5cce4e3e22ed4c59a3bf153f30a92c505410e4894fac38c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "f9ae5cc528ee43113939fc156e4b8a3c2c659c3d"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "5f4873bd4a76cfe437eb03a339d6caf4c5c981a00634252c93c883b41394b6b8"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+1/Zlib.v1.2.11.arm-linux-gnueabihf.tar.gz"
