[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "047159e833ab85ebf8b344a52b92a13f1b44d1ef"
os = "macos"

    [[Zlib.download]]
    sha256 = "58a6725cc392e0a55ab88f7410dcf774fd3c0fafd3ae036112505796ee73b5b1"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.aarch64-apple-darwin.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "0c6c284985577758b3a339c6215c9d4e3d71420e"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "bf861aa618865fb20ca228c42370ca6bd6aefeb5291954f7c4cbd28b0c9a5a27"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "377fed6108dca72651d7cb705a0aee7ce28d4a5b"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "c251e8d40c756adc41abb5e1f1a6e8663c42d491ad2de87ad8e3a0901c425a52"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "35c69c6c920abe3002f30d4df499e3cd958aee09"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "30dd6a144a1281885119a105393c3c49c96db84bf9e5f64ec8bd5ecd329313f8"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7019cf5e79d3147cb132d70e5e599c03ecedb8c4"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "89fdae8a411f5d6b009d4efc2f1328941b50b4ea8610367ed15a2b20a044b65c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "68112b5a8529eb286600242e0bb0b4660dc0f69e"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "d318ba13608b9bce234176c693d465f78dcefc3f0edea6558ecd2041349a8a2e"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d727d53f99aee4faed3c3447ef080c0a4584a7c"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "e039a7ff167a02fcf2aa66544c39120c15250405259053cb4fade13b647b36a5"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "e2c7906256e3799bbbed63fd4b722c13d91acc77"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "66404bf2b409f52a01a76e13e9903e5946ef73b8198889caf9d832d4c4c710fe"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "36f4a2f291c7d540502d2c582df637a07860a2ae"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "d9fd0bdaeb13217abcd26ce6ceaeac7dd6afd85c84eb727c368b6cbaa3f2968c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "ef472cd8d1d589c61d239a53f5970d3cdc18b2df"
os = "windows"

    [[Zlib.download]]
    sha256 = "2fed6d4781e0e7d32d3ddfb1c33366d8250c7015c0b10bd859b19eb83c320451"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "10ba2029939134fccc5399818565bdff411ccaf5"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "e73e8d611ac5c850b796dfb637ac31e5b9ef2e9b9c7e2c93f504c74987f50ad9"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "a037623fab6c40035f49e47f7c939987d2a7200a"
os = "macos"

    [[Zlib.download]]
    sha256 = "3d8d88e52907878de6f4361852dfb51f493f4043b3590a4f8f238170381aa97a"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.x86_64-apple-darwin.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "66cb477c2221860067abc2197baece8d67be5bb6"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "46678eabc97358858872a85192903f427288f9ea814bddc6b3e81a8681b63da4"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "b86177a36c8ba482120ab766b6670177dffd72f3"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[Zlib.download]]
    sha256 = "cfa0801e82c621511ad0ca0b8594fe19211198c3144fd2c87aadd48b66d5d106"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "d4212eaa51b38b228b3238013323a612428c2f81"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "9878bc6a6ca7c5386de0af7e65be232929da00dd5cb279b89331ac8c28e68946"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "19e16d3a2214b67d66524a8fe7a89ca0a033b47b"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "d73e192bef083cc0ef75da7d85d7c9a8453c2d14fdb2afbedf9c82b4826c8c2c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.x86_64-unknown-freebsd.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "70c46814df14fc801299ae69f463aff3f03f9034"
os = "windows"

    [[Zlib.download]]
    sha256 = "8e3000a2638b7610318051b90b4e79285c67bcb733b96da5452b622c2b2cddbd"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.13+0/Zlib.v1.2.13.x86_64-w64-mingw32.tar.gz"
