[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "c5bc77f6c13ea53905a53008947de2e0faa86413"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "40f7f7223b914cfb249ae8f0397daab5f7427a924311fb22886047eb961736c8"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.arm-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "bd4b3500383b992cfd68cace91460a99f5c3a843"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "3a70bfcfe31d43bc40863bdf0cef70c06563dc9665ed12173da24a1534e18c2b"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "75a45be561896daedee71b491b130f90f28da6a7"
os = "macos"

    [[Zlib.download]]
    sha256 = "92771a3f907877e947c878e170d31751f85cae0829db7de0c0a22b3cc08adbcf"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.x86_64-apple-darwin14.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "8c8062e76a97edf2df3eb086f9fb2f0604f61910"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c5064dade1ced139e5feb055d53d7487fd421a037d46bb800eaa49e55149fbff"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "de06a38721d786ea7f9c538a9c87bd74538d3379"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "3f274eaeb22e512ee2345807b6937dcd71a6fecd0ec67b0d73f3f855c7c25c70"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.arm-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "160b525f0c182340086af133b87f8f2be101d203"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "667ec533243ef73d8dfa27351b125df11346baa74ad563ffc234359cc2a58cf6"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "3cbc6669241a1166266a0c36267b8e7d0bfe8dbb"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "ae93c03ad75a42a1cf269638a16422eadfd40562cc2aca1f888e7254c0cd7c57"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "9a0c1045c9bcae57d0983193f3fa5fe157388e34"
os = "windows"

    [[Zlib.download]]
    sha256 = "a91ac2faec1bd091df5ba859142934b1b4566f730c446db4d52c654f084e42d4"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "52b0bae52139fb044ba414c6cdfb85751bebaeba"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "8462f173e8dabd6e8e391841b9ed13028599dee99f210780220bad9e58a59f57"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "7d4ff767fdbd2da6535373a7a67206e2925338bf"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "174f6f24d22c30457598c343824148415dbc7f9008e4e7f7dede801eff546652"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0e92e2da8b47f05f14eae7dc9bd6d95e1e0890f1"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "6aae044acba240e4ec7c72d8cbdcbdae1cca066b93b85c2954951a448453495a"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "71590707d605b8b083c7122f2ef0c6f13d23c450"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "284b708da5ff8515937a9fb6979b8eae5c17247c5bf0634be66591f8f6b4283d"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.x86_64-unknown-freebsd11.1.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "d57b30a8adb4f1628419d019c0ef0408b7811afa"
os = "windows"

    [[Zlib.download]]
    sha256 = "5357dd66ba4796e9f512799b2384e85f9c8184f3e0049c7df79d20ad49257ea2"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+7/Zlib.v1.2.11.i686-w64-mingw32.tar.gz"
