[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "e5bb0051ba8d2b4c1c1c81fd4071bcb97f1b4f04"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "44b3b3624f7d9a7053080903244cdff64bf1ac2348e58453898faf8a66e40a43"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "fd37df02f66015da92b978edc4729cdfd0c930bf"
os = "macos"

    [[Zlib.download]]
    sha256 = "7575579c34685b8adcf05663e2ed7abbf7e931be57633a978793a514e85346af"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.x86_64-apple-darwin14.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "cc108441cafbb3ef52ecf209a9ac70385c5ab8c1"
os = "windows"

    [[Zlib.download]]
    sha256 = "4a15f78d2ca5e87c34d58153f06d5bca9463b1e654fee71f729f1b1ab8d254c6"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "38850efbe673067b721bde7bd322ddfc6f06480e"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "4bfe5bd6bf32c532f416b6e039b46e51b4e48c119840592c710ad50ce5d11333"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "48cce87c1e177093f35e93dc6e8d1c80028ef27e"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "6194f1879ab802a194132f12593d2c21041d5917354a19000cd287a20a399aa3"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "f5bc9a26c10bb85a38126faed300afe9635f6c7b"
os = "windows"

    [[Zlib.download]]
    sha256 = "754a702d6f158b48621be56b590c32bb00357f8738f4ce99ebc4364a3058d80c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "fe50e918f0cb3737f72c86e2ff5a593f24ad63c4"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "dca25ec1bec92318827c22931152bd12aec37c5dcc789e433c19284d4ad2ffd5"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "ee9bd877e9d7f6ffca32757a89848436228412fd"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "bfc9e508064af08f016ae53caaea7f84c45453dc00220540da5cb694e49ad0b6"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.x86_64-unknown-freebsd11.1.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "bc5879b118273e0be1ae21d7bba5ecee2c5cf902"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "7a3b3bde8ffeffaee8f95d2b967b1d0a90c1cc48cdaa57a759f0f97c4c63fed9"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.arm-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "af467bf265845026321df9a3c61ed5208910b5d9"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "0c3e2a6261a901857c2e22f725ef5c277c9cdae0710d637c195a86d187eb123c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "e2225cae499151955ec39aadccf2e885a056563f"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "d9d28ca36563672fc2fe4ac6b0450f98ff1b1ef60f7c78214daf9f0c699195b5"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "49bf9c331e17b0f57d7da19ddf817ec8989e9d76"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "d7538c454cd3fb2fbdd5331cf1aa1a5ed948ab764d86e3330daf5f69162644cd"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "304bad28b32cc3e839fb3c65a4c65eaafd69df8d"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "b5e96d2afadad8e38b877391f10bcd320ee51886923ec6e1f2818cd263c7c655"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+3/Zlib.v1.2.11.arm-linux-gnueabihf.tar.gz"
