[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "1e222231c14f90f02b5d7028ffb250b49c41588f"
os = "macos"

    [[Zlib.download]]
    sha256 = "1dfd0f34820d32d797747428984ed8dbbd7854f4c6c0b34ec123bcec3fbb1d22"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.aarch64-apple-darwin.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "8ed06e5ae0602d8f1dbb8fe315d313d7cc8eb6c7"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "b870059af8b7f012be552694cc3526b9a47d92e9e6c73036194e8c38c0cab3c1"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "716fa16518753da906ccbe151331a20b662d6318"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "48aa6c7fb8458b4c2e7b505d7611b4c368cd55be4585d69f0c65f7fe80ffed00"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e4f2723523a92d51cf8d8caa256224bddecef95"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "116287698826f7ca75af8a3d5ce24d4d75c784d629eafee5c463eca064bcca9c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4dc73d1a2d299a8ddb15d128a89334ebee6e58d"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "4d95e8ef1a222466cb0621f9f23849a9d1f836f772d8e5f8f06181fa7953f89b"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d060acf3e5f603bf11a057c1b102c3de3b679bf8"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "27779e4a315f5b6a7a4109b2bf53d5f2da86fe8b5a68fce8718d484e8288a8bb"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f3664a38c2b00be60c97510ecc04dc664b9d3e6"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "5a16545c8715998534d7b5787ca57119108b335f7332c08b528399c50d7c6ce5"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "82862de3fe1318d27ddeeb026e049bac27bb34dd"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "fe2c738c070c08839163f37fad76ba3e2a714bb605ff82da67776b6930e536e4"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "8e435cf36502e9693e39486451c2fb37853cc6a2"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "6c1a7af3805937864c1142ebfed57909e7fb50130348bfd5e90b38499dd4799d"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "8a459a55a2c2f784e5bc8674f2e37b1de63b3dda"
os = "windows"

    [[Zlib.download]]
    sha256 = "a6ff3e6115332af3397c8927e871793f3a5690af36ab60fca4b11a432ad57953"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "24b320bc09401f57af5c8f970538aab177ed3529"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "3d60005194df1822d73988f08ade4a86381f785db9523aa8e2c61fa47205ea58"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "a713334eb315d95f3dad659bed594cb2fbbb668d"
os = "macos"

    [[Zlib.download]]
    sha256 = "2dd4d5698d3742458b1882f1fdb5ce897b0bab8b2fa5c1d673bd92763c6c3bf9"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.x86_64-apple-darwin.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "53e6c375d00db870bf575afc992c03c54cba1d7e"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "4149b5488a21c3243f954343ba120c294781a573b0ba7b28509e72d6511d1484"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "96694124bd7e77128175b338316c881b0bb46f95"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "4a940bdd84f87bb82fcc101174cddc866d882aca5329da586080a644b89ecc49"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "a3c5902fbfaab3b28df6ffa565451786b6079d6e"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "831f3097c462057bed2606ad5e371dfe7da6f9df5b7eff3fa05ecefbfac141dd"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.x86_64-unknown-freebsd.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "3bc1709f8cda1c4c44d442434022b3834d1d36b7"
os = "windows"

    [[Zlib.download]]
    sha256 = "5ac85bb44241fb3ed286d95c59e07d740bea4c865271e01cf08557e2b45ab217"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+0/Zlib.v1.2.12.x86_64-w64-mingw32.tar.gz"
