[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "a093ede5f4d8d4e62c8402ef98a604363a9320f1"
os = "macos"

    [[Zlib.download]]
    sha256 = "c9bb1d0d075d6d72f5567cb4d5f7b862b7748c2c1afeed1048c91b409092ccab"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.aarch64-apple-darwin.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "7c5c2ebc097921847ebef9b2119c7c52841539c8"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "593583e81e16e07f02d5e0a1408562dfe8df2960cb3c9193c35b6f283cd278dc"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "cf1c038ce60dd07091e643aea820806b9070244a"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "4f18a3391c999d221aac9691364d5716b57143b2126b4486a13d9f7d186ff8b0"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f816548d5996af8ea45be8ab57e250bc3c23f319"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "4961c9ef04a60453bf1f68e919f2068e601cdfb81b4e5c2c28acdb4d9a0589fe"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3fc8ca509218f5ee3d11ebf1723db14aac674ecf"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "02586292a673b421c4f07a44df164cd68e7a96bfade4628356ecb6eff3c945e3"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eb5a7fa39ad1daba5b9d30bca388b30f6f759619"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "edec9801f06e5985a49c1bb1fd3263415540701f3ce6a4da45a2077f44b913ef"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3f29fc074bf574365db53095823f8c317ae53094"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "7b57a85ada279b1dc10483303d938e69153432f5247d3aa5e93e29a4604e75fc"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "1bf62f25992b0a035d8a1a962b87acd64d7df87b"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "634112532fc49230a75a114fd8f6d5155d1fe8fef682b2635e55f0ab430a9e25"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "bd5d01374913c5dadefbc31040030e2a766f1c26"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "54d31dfb46f7acef39a2c74307fd99d3b8ce06a1bfc4ae8c36f3213838546949"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "a04198d741c02dee27b3a3a58b0ddcb4ba75f254"
os = "windows"

    [[Zlib.download]]
    sha256 = "4355de7b5330ab59cfa48763caad89c557ac348705c971df83c08dac9f1c4356"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "33d22f3a34dc3eee4c1af459ed16976ad1f91f38"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "4746276aa69af573f05c8a89e67dbf9827f459b6aa650c2e23a0ad8b2fbb22a0"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "b63c64a6fcb8089fbeb5b4558fb388d4c6f66500"
os = "macos"

    [[Zlib.download]]
    sha256 = "c7b4e22df9ee8a3da1113a95c0629e49a1b375f76ab33d0163d560072f38cf41"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.x86_64-apple-darwin.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "16c49752d702a4cd9e4ce455799c958453a64005"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "dd24de7baeb0ba4216dd91ef54948b0a5a0fd16e694bfaf5534c51cd14862484"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "f87c4c946cf36af69f43f03487b077332a8c0411"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "ec40e2696761e4a06f3a3ba88daa2e1657b5ee99bc85226a9bba138e9ec2727d"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "94267816f10ed8509d8481f42d67e7baba0b49dd"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "adc11ddd0297a5e92828ed5dd8a562637b7f23d2ebbff69ee9049276b0082808"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.x86_64-unknown-freebsd.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "f6f95777975ecb4d3b39da90888725a237113082"
os = "windows"

    [[Zlib.download]]
    sha256 = "8ed4b94e6c7438203970a60b31ed593d5f54467c95c5c87a52ca8335e0f10c7c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+19/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz"
