[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "21c6c94e9e7c49ed03a5d89e578f120ba3174b35"
os = "macos"

    [[Zlib.download]]
    sha256 = "9ba5fa7c91c377d675f77eba38a3e38e20dc200fbaf79519cc3d50fa94ac2de6"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.aarch64-apple-darwin.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "ad72916da2ba06c8c8b457ac068955016ba88960"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "de53df733dd6719d1f368f32fed6ee665289db9f7091b0a5029c704a05ccb893"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "4a3d180fea631404945173d919f1a829697d2488"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "fd75af5ad76881fb4388ff19bc044bfc3bb8aa90e3726f251a313978bcb2ffbe"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "006f44b2a9eaad17ed79a75b7863946ba7f28e35"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "0ff508877a0e3b704a86164a1118cfa4c8ae846cbfa1adb35d446bf450db8c89"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.aarch64-unknown-freebsd.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f09fbf3b372065f564d02d231ef721ba0936b98"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "e3581e2b3e1c82a69a6c392af0af9c8d75bb03def5df619c6218110aebc47128"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "217e970644c451256efe5e0bf0f68e4019845c96"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "655bd3746783080665b33f2b65d188dbee26b31294d4b9f00fb6ef9aad7996d9"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c5d77fa01cf4033b281fdeb6dc957cff3ee0bf02"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "9bda2109164fcb1bd327fd07602a93af8e3c2643c140eb7165d56faa473346be"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c4f31084a14c7482a33df2ba12d95bba2dcdf997"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "9c9007fe37da5a7e916da900859461752105eeb66208d6b78da4049361ce6c95"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "4c57cb09f4337ded11b03771612fa7fd7c4de52c"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "7fdd765f4c00a388d96b56643ac8680f5aa2fb3eb5c6623c48dde0a748243255"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "1619f718ffd7abe52a2105637d884d0a3e8ee863"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "ad42c3c5c656484384d1fdbf6212306c0a6cc50014f4b664af281d752991592c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "28b3beb519d1eff11272b47bbc31499481cff1a6"
os = "windows"

    [[Zlib.download]]
    sha256 = "0b0f6bf851bbf5c29c017863d2e78124a9bfb47f2e8131df0313a2a2bf764096"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "304ff25a7504f76af0f1af85dfa8ee18d2eef7e2"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "11a0ba688e01cb7d2bfbae081620df3e13b335976addda8a96503e883c45ea3b"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "riscv64"
git-tree-sha1 = "ad786e605250fc27b859347a1b79991fb13ae4ae"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "36c1b92284e8a33182d9109b739f78c2b918558b46e856dcf592c2fb77b23836"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.riscv64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "ff94f1d3f56bcd3c9444536b870d8248f84632b5"
os = "macos"

    [[Zlib.download]]
    sha256 = "0e1cb1f581e609df619ac01f346d27f3c9a78b5f2b799892803897e1a01dd98c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.x86_64-apple-darwin.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "438377fe76907b3472fe256e7189bcee5430637b"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "b57731b8287649972b9bd730edb25acfd66910941c541473eac807676550d0d3"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "bf13bfa936d85ae74d0fcdb5992438d0072643ca"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[Zlib.download]]
    sha256 = "f3ef617b6f8c2b644495982e3772e7dc18723ada88b36e41f79c52fa03a3ec05"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "a7974d0eb98ae4d9c67e9fd41b97182489ae2b9f"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "1f1c37b8393ca80f200cb3773c5b9565dbd5f04b85ee4e3bb3c3b36fad20b216"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "50fb7b61fcb2fedad8ee37abcdc1589656031c01"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "3f11fb5b5753c164e772b9e6ca3a8de734c5c40668fb2dea6109b9aac50f9b62"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.x86_64-unknown-freebsd.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "582a8e879916a111cab7838f4166278b9f84193c"
os = "windows"

    [[Zlib.download]]
    sha256 = "c1237a6bd638dc348bbc4f06fb022157fc4fb0a009aacc04ccf1576b152e05af"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+5/Zlib.v1.2.12.x86_64-w64-mingw32.tar.gz"
