[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "42de4b544aab930f2962eabd8efb5cfbdd9be8d6"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "af19488cd5a568c6df3aac8aadeb37ecaed0098cf7ebea3b3737f80a9f63fca1"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "8fe6df8efa7a8cf3055554e27372ef19e671e1de"
os = "macos"

    [[Zlib.download]]
    sha256 = "580185f19e4910c2eac4e025e143cd009c238b872efdc5bd3f2af4ab9fda8edb"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.x86_64-apple-darwin14.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "08191986e13a853ee5a9b91925b077dcb4d497a6"
os = "windows"

    [[Zlib.download]]
    sha256 = "275047011052b7086b0183a366c5c271a58a8be6c3fdacee8eeeb6566d28233e"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d0c0061a7256bf4c7f876fc6033302487f8eb938"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "7d828fbbe005d2f6e1ca1cbd4173f57dabffc10282868f9297261716d69b18a8"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "6db17f1a67b71c34d81488ef646f792aa6d3e563"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "fdbe2168a3d0b72a6e6fe4350b27cb690b03afb1445e027c44b66f2de637cbce"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "6aaceefc3d375e81f51936a0e2d696ec4accbb1c"
os = "windows"

    [[Zlib.download]]
    sha256 = "3b2d306081d6854a020d4b3b4833d231d889819e389615fa2e69077a6ee11322"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "6f4aa703cc997693bda2339b8f93ee294577b6cc"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "034eb78ff56d2c0f53736248bd131c9ef0032bb4ceda8492690fee407222c142"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "e1b039bb23181acd39cf1497271975ebadb49230"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "60c68e48661741fbeaf5bea6bf908b8116450aa99b0914d49d8d0acb5e0429a2"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.x86_64-unknown-freebsd11.1.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "65d935dd38b3db9740b9bbe882dc8e1f4f25d583"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "521349d527e6a9c64d4e6b3d65c589a74ce96797eca1004752c2ea35775fd4f0"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.arm-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "c06a48d934896a2cce1c3791ccff1d12e669a24f"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "5365c27ab6a77178cbd874d43f2d1a9693a42d492b8611027a66159b099c1b25"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "ccd16e241fb18cca09409693f44f6ef1dc41b3d4"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "4f7741ce37b9505570c4917b1b8da640de2f2c145bb5f753a0e3850c8b125d56"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "5b6af7729dfa16c3c3f4e38ec75ef456f64ec1c3"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "787d3c51fa5c9bc5e5271d1fb421cc2f937249fe51f05fe72e5d22364f2cf18d"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "89e8e2952b8d012fa616d0d15a508cff93acc7d9"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "f95d2dce4f0a77b6c058bfb820ab1d085a6863aab9f458fbf125ee604a40acd9"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+2/Zlib.v1.2.11.arm-linux-gnueabihf.tar.gz"
