[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "84a29f0631f94e0cdd2d7f7cfacfa779b5e99163"
os = "macos"

    [[Zlib.download]]
    sha256 = "f904ff92e92d3aa613d0904f5753f9fc3e6ea0f810de9b57910fc51988ed3502"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.aarch64-apple-darwin.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "78c13dfbcd23d62d5f5be70fe41fb9b396350931"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "318407f53c06e038d6eac0316342125ddc080a888d4012cefb2f4587a4378d77"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "12a60e44184ea00c8fd6345961220c6a3c74323c"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "3e0cfa141bada795f402e0b409580efd60687ce00f216336550a554c270355e5"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "42be56d6b9ca663a669838df81237eb3b3fceb23"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "9529e94d35fcb60fe7797e8b1a30df080d56e48e62e678ac6f18b3dc820d3e73"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7578326c50b1bd27557a2440a4785d19b5a2e34e"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "0eea4ec303522a69d83b7bd02ea2f53317766d1b0e95476765346375820ccdd8"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "93f0f2b5ccf12b8531c86b1d057fc871043e8af8"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "b2ae76f59f7250b7ea018983eb623bf0685a15de09d998d06ac8b3e80d46ce15"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f6d7527ceee8229d15b97b459f0fd635b07245a5"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "af65a9e4657e817acf4aa485896c11e466cecaa1197545612614621800076f68"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "b6d98636e5718201da4c12a23f37fdcfef2d9ddf"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "0f961e256e2392bf9c5c7dd07ba80294c7f110526eebb6d17f396c551e6e8b87"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "f307a7a71bc8d9c2afe8c4cc1118a329578dc0ca"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "6c6a2c967aac5dd3f1ca9f6c3986871c9731333b1f4c6ea7f43458ff1d54048f"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "cf5d9fb9da10b4fddc3945fde9f34f50f469433b"
os = "windows"

    [[Zlib.download]]
    sha256 = "d2dde92d61b414a7f948eb618458b46f062a7f343a168d4ac73405c7a1d9e7c0"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "9dc39fa950d54a33457eb8a72dee103097e91c5f"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "87bb033379877fd3230904b9cfe1317f1392c5eca96fbd3a16584de3736fd685"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "cdc165932ce4770a8a506365e1ec35183ba0ffc8"
os = "macos"

    [[Zlib.download]]
    sha256 = "8d198b9c46e0c9ff9675d6839b83fa7e99802c5a672d6ca7f38ebf7b8e1480b1"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.x86_64-apple-darwin.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "f676014ecfe5b9b9f9ad71fabbf586cbf47898b8"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c63c558629b7ed6c40ac642889023b1f5b6b95528313da40e85f65e1dc7ec26d"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "91f4222f88ea71cd044a0d6641cd566acd22b5a9"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[Zlib.download]]
    sha256 = "236791dcaf56bdb340803521c6be860157db5e92c7ac97bccc03e70bc7c0b9d2"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "3b6332728dae493d7976e05416e6d72b0ac19fa0"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "0ea649f85d0e1cdac84e88635e6c81222d941fe566deee9da9b7a367154d5094"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "e51755704a31486d2942a98de8fea20a510459bb"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "2f13e423028abda3cbec7186d884ce8e2cd221514992795ee4daadf481cca57b"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.x86_64-unknown-freebsd.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "4471271d2b1deb5b3b717297057615b9383b6418"
os = "windows"

    [[Zlib.download]]
    sha256 = "f39d33526956306561a6af893b7af3ffec9b55f1612a3e8222b0661363f551d5"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.3.0+0/Zlib.v1.3.0.x86_64-w64-mingw32.tar.gz"
