[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "9b08c7515acef64eb19472e0886046c78a21e329"
os = "macos"

    [[Zlib.download]]
    sha256 = "37bce33c07b66eb6127ece18bbe30b770d009ad2121c5e70bb651dc2fed22839"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.aarch64-apple-darwin.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "2d86c02012a372a2607be5c754c4eddc9147db6e"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "cdea2ae80f651c4753bbb8720ff2dc86c898d959e14b40855f673ca1d193cf8c"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "d8e11e9fe8a59052323f2a6c57df1b55a09d83f8"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "14aee2e3316bb96687e2f5cfa912a68b12418d71b03272b78f70187eb6b335db"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a63fabf493c28fc4bcae6f66d79928bc4d2d8439"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "51bef7dd4b00c570b8bd8c540504dd0f9b1c41d3768f42285aef4423bb08f4ee"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "766daf11ec1d95faf565efa97e94b03b8bfa12b2"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "88b37b686bf4c10ab0bf27e82e2d96e8c808300e826e2621bd4d9d0bf52e0c86"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0eabccc2d9dc78663466e075637de4fef7c33657"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "84291a45513358c5badb7c5ab58adccb2989130efe5dc1a8a3a43633fa7f0d7f"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f18bec64ba214e5130651c63393d27e43a458a28"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "764bb92c25ba2b7cb67af6f933538686398984e79240c485aeb651582f853bc2"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "feae542f651de60a8171ab187b0781b12a2d7a59"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c84568ebc6edb40f1bab19c565624360a8c7ddcfe4dd57b6f2dd753c51c324dc"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "eb1713c9540525d385265cce0933e3a1845a618d"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "1ddafae47ef21fa2551d9a7e6aeb32050c768493ec9987abc9ce1a110d328971"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "a5e27bac1fd7d859c7ca7c967fc883a1a23463e5"
os = "windows"

    [[Zlib.download]]
    sha256 = "0d49e92b02f68d860f40e1dd461732d6f1f71365aa1aa4b652eeadb13cfa092b"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "ebb4973bfbaecd4b9ca69ab2a4a4f8d65fb51640"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "7a229bf9514032e67c02965206d08f3e87cf496d13a0888d6fdd852fe2595f78"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "6ddfd240f2d653c8a0fb201e31be7d6015283a7b"
os = "macos"

    [[Zlib.download]]
    sha256 = "f400f0bc6846600682b13d2583a9a3503b0e195649c0d4433bc1088bf7ff1215"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.x86_64-apple-darwin.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "93ef3ecc9e14651f000a75ac4c702e119102ee2d"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "dbae2b82866edddbb87524b459b41b920e0d537efec06ff7ff022cf79f1a1e21"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "171e4ab5a9ad2dc5b15ccb70914baccf780da417"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "e1d5e877db501ea37100eba04efdb94430f4f35b03f27128ba4a54c3b0e18aa3"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "6a6f1cdf86e5ecb55b40f0b1367832170237c399"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "57be6bac6d817f16480dd5a84e281fa536fd8e085395c3232ada47cd814a58d8"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.x86_64-unknown-freebsd.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "a6788e4488004f336523696262ce75afa47e08e5"
os = "windows"

    [[Zlib.download]]
    sha256 = "4a68eff08b14bbe2504ec24631f67d2aead2cd3faa7556b5cbaec941cc793f83"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+2/Zlib.v1.2.12.x86_64-w64-mingw32.tar.gz"
