[[Zlib]]
arch = "i686"
git-tree-sha1 = "c8456cbd00982236828623bbc63f21b9b7b03821"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "2297b370398fb1c2dcc966eeccdbffd9960497dfda9e223ffd41bf7231025a27"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "97d349ea04aac1e300b0411ac5f2df320867bbf8"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "7b9664abc3d390c2726caa8957154700268045eee4001f9db4f89f3a76d40a75"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "e3f15a88ba19258a63146f7ceecfaf93c7bcfbc3"
os = "macos"

    [[Zlib.download]]
    sha256 = "10045ecb5ae2278ee3ca1549cc27dd30db42e415bfd6978e68572642f9396e11"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.x86_64-apple-darwin14.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "4ad8583181823ba1c9455eea9cda6085a7ba3ea3"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "53579b8eb2e542d88f05861ccbc4e04c95884a47bd23349e270c433f921cf418"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "3dd0c7cd5424c8746a1a32034ba1b10458f20b3b"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "dc3449f9073750cf574530a0e19a942d2e6a721b56afc29b6b9c247f09c2a420"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "0e7be4a1127cffe769b01ddfe914b3fff62b00b8"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "3a19413626d019ace52b39ed3fdaecd721778ab51408bda7f68575351c8fb256"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "bd6c05f2e516ca72673f6856ecdfa8c47ad89587"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "27aeb30f125423695320312593dd17c8cf67dec635a337df0f218811a76d873b"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "4fe9665c24b2010f28da12875c7fbf459689cecb"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "a22637e5d66a9b4ba62bb18642e2d6623243a00146d0d29f6ee049e5d4e12045"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.arm-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "7c13253b520c2c20423b09abae5436e0403b4812"
os = "windows"

    [[Zlib.download]]
    sha256 = "d3192db395f15e61105f09ad06928657e4e934d54e7d5d7aceb9e4672c1f4193"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "057a2f422d1067909b5f199dbaa7d2b8ca76f277"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "48149a62b13ecf52e5b6eb258bf37aa5db57305871fcb5e029e2a0b5140219f8"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.x86_64-unknown-freebsd11.1.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "748c38025b5596a5005a87ac2b9476603cf8615b"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "af5c8ece6392ba048bd6d1e1257a4068ac6c192ad0aa5f6bef3879ed03ac11af"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.arm-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "7846a2956a213715c2c76632f3461cef87d9d545"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "18a8553dc5335b8c42c1dec0e5fa055bc5badcc0591ee1dea44737b2c34b548f"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "a4cc652bd89accda4a20d894b77df68eae2a95f3"
os = "windows"

    [[Zlib.download]]
    sha256 = "99dda782d485c18b854ea24e7749ea78e577ce86038f85c53fd2067a03e39661"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+8/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz"
