[[Zlib]]
arch = "i686"
git-tree-sha1 = "e0f655600ba9a64d6b5f136493d97b260ed591d5"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "8645b4dfec1b17740acbc37cdf3e45caa76d689d144f9fefdc2c0a3301dcce87"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "497a099744d4e917580c1caf4f71674780dabdef"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "6fb52e3e71e68326a90300f00f819205ba54b41590e6523ecdfe8d09803fee7a"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "173b135bcfdb440c6e8a28fe2a59ab9408c6914b"
os = "windows"

    [[Zlib.download]]
    sha256 = "f5956e7f5f017e967b3e32c13158f0128b11197326f54b08865c34d2de6fa800"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "12dda53f058e2ad8360473e1df8d31d709724a38"
os = "windows"

    [[Zlib.download]]
    sha256 = "630fa0b1921c5b01d1433f5a668e363bc93fb529fb08cb13f11131022e362933"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "571a49beaa782c9e42a6d9dba5d9e49964c89cf2"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "d58934fb4fc6473b64dd10e3d66ff8932ec648bafab97bf781260c7847076a4a"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
git-tree-sha1 = "3f9aa30edd1b7a0999ceb37029f335b6850fb8da"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "dba64d2b2c0faac2c5cd69d7ba2cfa18e767004d540eaa802cf94d4ed47cbc5e"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "4fd249648d83c00baa30938a85999f295f4ce0ca"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "5a1d21b177a7e79e6ec8fd1fe63ff635c580f0b0944f2249454a127c39f8effe"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "160c4caca0cb15a9cc6e5305c474ca758670160f"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "14674787b426ea485e5d5635d20a38522383180635ee819577033c34b961d55b"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "dfa503932077c14ac30168fcc3f61b7e1ee9c68b"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "f057017cebac5770d3738b1229e8d7278191f2cff4aa3ac5fce8159c163ad908"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "79152dad89b0add0d4b785694eca0f62247d940c"
os = "macos"

    [[Zlib.download]]
    sha256 = "ed603b0d09e5f7591d7a0487a171bc91c8e3951a8ff90bfcb0cb77a59d3d789e"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.x86_64-apple-darwin14.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "6084a3286aec50c61aee25beca987837d040ce09"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "01a6798aa8c6fe9373b947c7de0560bd96450aa7ce2cdac18fc8712470070aa3"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "4d22d8bbd592555aafbf8506728190c471b261c3"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "4b1c7e14680f565650489b524ebb665630d5443d31124205ab2ce1a44878d4cf"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.x86_64-unknown-freebsd11.1.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "5cdc7f45e686000316d0e4766a946ce87d36f834"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "f7a40745b604488bd511c0d27a856a882119a6affda22ec3f2dc6f5f5ce4fcd4"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+9/Zlib.v1.2.11.x86_64-linux-musl.tar.gz"
