[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "8e2195720e8b4ffbf6cfbd7499659031653b6a5b"
os = "macos"

    [[Zlib.download]]
    sha256 = "1f1fb5c5b3ae6478a2a4f06aab5df8a761a1358fadc1d836ee4ed28174e52465"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.aarch64-apple-darwin.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "abca6c5123c01bf6aa7480cc008948d3e1483175"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "756a27e276af5ee202396967a9ec423ff3ecb16ea7f46706a505270752d39659"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.aarch64-linux-gnu.tar.gz"
[[Zlib]]
arch = "aarch64"
git-tree-sha1 = "ca0a9c539ea8c50b3782139857f5860e6d687d85"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "d7e37086a2b775140adce56ee6794b004c4d7bbeba3a09f1f9962f64e1ff5500"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.aarch64-linux-musl.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "52a06ff9ca396bc8a3bd36a0ff00060271484fd9"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "653f137c09815825590261791a01e9946a4d27c22ab9d63f492e8ea0375060a8"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.armv6l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f0b68107018c2248155a32261b88e28ba60dbbd7"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "8ed31653b4447967fd985e4ee22f03fabc51ca925d2bf9f295b1c7226e291864"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.armv6l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c170ecd869ae20348d7b6329393dad3ae62a926"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "c3052a1af0991a466190e9a422501b8e90e45e3446142ed5880ef1d1e5dc310e"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.armv7l-linux-gnueabihf.tar.gz"
[[Zlib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "59736eb90df2fb698058bd0dca5c92e156c249e1"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "9c3d83de14cf2d1f5d8b891ca8c8fe91a5605a80760b32f4c7ff17144adeda02"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.armv7l-linux-musleabihf.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "34e165fdc826259e885017451015a946f4116969"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "5bcb4549b2d2df03d044dfa8de0191735a7fa8423d3d67c857bba42d8ba19a41"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.i686-linux-gnu.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "f47261673dc8bb6aa70d4105cd659720e93bd731"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "eeab065ee8f4abe2064176389baa7d48491be1b4941f1bc8cb4b1d128e38009f"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.i686-linux-musl.tar.gz"
[[Zlib]]
arch = "i686"
git-tree-sha1 = "642668a93b3a52bca9927e36bf573ecfb9d35e3e"
os = "windows"

    [[Zlib.download]]
    sha256 = "948d2ad542cc1417dc836498f5c360c6def7463743eb1e86de39b01d0f4646c3"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.i686-w64-mingw32.tar.gz"
[[Zlib]]
arch = "powerpc64le"
git-tree-sha1 = "446f9a574fd851def703a1461f05a9cfa10df3f6"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "830f12fa6e0ffe41fd6b9ffb38b332b776a69ba2e8a82a10dfe10093642f68c3"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.powerpc64le-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "c952359687b65cb01762b65c9877840ee1c80cf4"
os = "macos"

    [[Zlib.download]]
    sha256 = "4db75c47ca11b5662b201bf52c3ae9e95da9b0fbb69fb6129ddab0c4dc2661b3"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.x86_64-apple-darwin.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "8349745f7783717c8509f71d5b1676ff1128eb6f"
libc = "glibc"
os = "linux"

    [[Zlib.download]]
    sha256 = "e9368e672263a398cfd5a31419a36663e5c7af8a4fe658bb38b0cc4b86b27fc2"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.x86_64-linux-gnu.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "e952abaa36a5ebc7dfe96330124afc2a12dee6e6"
libc = "musl"
os = "linux"

    [[Zlib.download]]
    sha256 = "72d1bfa5c7a33acf7f0775621c3580d92b7ff6edffc339a086d35e946bd6cee7"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.x86_64-linux-musl.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "bd9dea46fe0d703d78a6232c63f1e3e7f4eac0b8"
os = "freebsd"

    [[Zlib.download]]
    sha256 = "8c221440ad985f088ba6dffe69c308b6607a729b95cccfbae5e1582c11bee079"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.x86_64-unknown-freebsd.tar.gz"
[[Zlib]]
arch = "x86_64"
git-tree-sha1 = "3636b4b68bd394f4b113da5ac7ad4b33a71d2332"
os = "windows"

    [[Zlib.download]]
    sha256 = "b7574443eb6983349261d69a39d11eb2585672d10629d5231993f1a4f3b32c90"
    url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.12+3/Zlib.v1.2.12.x86_64-w64-mingw32.tar.gz"
