# Autogenerated wrapper script for Zlib_jll for x86_64-apple-darwin
export libz

JLLWrappers.@generate_wrapper_header("Zlib")
JLLWrappers.@declare_library_product(libz, "@rpath/libz.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libz,
        "lib/libz.1.2.13.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
